[common]
region = us-east1

[functions]
memory = 512MB
use-secret-manager = true
;service-account =

[scheduler]
schedule = 0 1 * * *
;schedule-timezone =

[envvars]
spreadsheet-id = 1VYYuowVbcYmWNW_LdDKlz6VRbxbb5_8J7C3cFV9zDpQ
log-level = DEBUG
;fetch-labels = true
;post-upload-action = move
;completed-folder-id = 1ZBdR8p5KzFKxvB6KjNeIKfTbWeaRkv-o
;default-video-description =

[arguments]
;drive-root-folder-id = 1cMlIsNLn7KoaMjHEZYjn8pavtQF43xAM
;youtube-channel-id = UCDhxapLoA0eGl7PJa4ZtTiw
