[common]
region = us-east1

[functions]
memory = 512MB
use-secret-manager = true
;service-account =

[scheduler]
schedule = 0 1 * * *
;schedule-timezone =

[envvars]
spreadsheet-id = 1VYYuowVbcYmWNW_LdDKlz6VRbxbb5_8J7C3cFV9zDpQ # Your youtube upload config sheet id here
log-level = DEBUG
;fetch-labels = true
;post-upload-action = move # option as rename | delete | move but let us have this configured in the youtube upload config
;completed-folder-id =
;default-video-description =

[arguments]
;drive-root-folder-id = ENTER_YOUR_DRIVE_FOLDER_ID
;youtube-channel-id =
